### ISSUE TITLE
Bundle Menas resources

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#314]
## Background
Currently, Menas has a lot of `js` files which are fetched separately on load. This abundance of HTTP requests slows down loading the application. This will only grow over time. 

## Feature
We should bundle our resources and serve them all at once.

## Proposed Solution [Optional]
We can use something like
1. https://webpack.js.org
2. https://parceljs.org (less configuration than webpack, an interesting choice)
3. https://github.com/eirslett/frontend-maven-plugin (maven plugin to run npm commands as part of the build)

**Comment by lokm01** [comment]
I guess this (for most part) solved by the component preload.

**Comment by GeorgiChochov** [comment]
> I guess this (for most part) solved by the component preload.

Not quite, our source files are still not bundled in. #478 certainly helps, but is a different thing. A bundler would also allow transpilation (and therefore a wider browser support).

Let's put this in the icebox, but not close it.
